// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package proto

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClientCmdID provides a unique ID for client commands. Clients which
// provide ClientCmdID gain operation idempotence. In other words,
// clients can submit the same command multiple times and always
// receive the same response. This is common on retries over flaky
// networks. However, the system imposes a limit on how long
// idempotence is provided. Retries over an hour old are not
// guaranteed idempotence and may be executed more than once with
// potentially different results.
//
// ClientCmdID contains the client's timestamp and a client-generated
// random number. The client Timestamp is specified in unix
// nanoseconds and is used for some uniqueness but also to provide a
// rough ordering of requests, useful for data locality on the
// server. The Random is specified for additional uniqueness.
// NOTE: An accurate time signal IS NOT required for correctness.
type ClientCmdID struct {
	// Nanoseconds since Unix epoch.
	WallTime             int64    `protobuf:"varint,1,opt,name=wall_time,json=wallTime" json:"wall_time"`
	Random               int64    `protobuf:"varint,2,opt,name=random" json:"random"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientCmdID) Reset()         { *m = ClientCmdID{} }
func (m *ClientCmdID) String() string { return proto.CompactTextString(m) }
func (*ClientCmdID) ProtoMessage()    {}
func (*ClientCmdID) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *ClientCmdID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientCmdID.Unmarshal(m, b)
}
func (m *ClientCmdID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientCmdID.Marshal(b, m, deterministic)
}
func (m *ClientCmdID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientCmdID.Merge(m, src)
}
func (m *ClientCmdID) XXX_Size() int {
	return xxx_messageInfo_ClientCmdID.Size(m)
}
func (m *ClientCmdID) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientCmdID.DiscardUnknown(m)
}

var xxx_messageInfo_ClientCmdID proto.InternalMessageInfo

func (m *ClientCmdID) GetWallTime() int64 {
	if m != nil {
		return m.WallTime
	}
	return 0
}

func (m *ClientCmdID) GetRandom() int64 {
	if m != nil {
		return m.Random
	}
	return 0
}

// RequestHeader is supplied with every storage node request.
type RequestHeader struct {
	// Timestamp specifies time at which read or writes should be
	// performed. If the timestamp is set to zero value, its value
	// is initialized to the wall time of the receiving node.
	Timestamp Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp"`
	// CmdID is optionally specified for request idempotence
	// (i.e. replay protection).
	CmdID ClientCmdID `protobuf:"bytes,2,opt,name=cmd_id,json=cmdId" json:"cmd_id"`
	// The key for request. If the request operates on a range, this
	// represents the starting key for the range.
	Key Key `protobuf:"bytes,3,opt,name=key,customtype=Key" json:"key"`
	// End key is empty if request spans only a single key.
	EndKey Key `protobuf:"bytes,4,opt,name=end_key,json=endKey,customtype=Key" json:"end_key"`
	// User is the originating user. Used to lookup priority when
	// scheduling queued operations at target node.
	User string `protobuf:"bytes,5,opt,name=user" json:"user"`
	// Replica specifies the destination for the request. This is a specific
	// instance of the available replicas belonging to RangeID.
	Replica Replica `protobuf:"bytes,6,opt,name=replica" json:"replica"`
	// RaftID specifies the ID of the Raft consensus group which the key
	// range belongs to. This is used by the receiving node to route the
	// request to the correct range.
	RaftID int64 `protobuf:"varint,7,opt,name=raft_id,json=raftId" json:"raft_id"`
	// UserPriority specifies priority multiple for non-transactional
	// commands. This value should be a positive integer [1, 2^31-1).
	// It's properly viewed as a multiple for how likely this
	// transaction will be to prevail if a write conflict occurs.
	// Commands with UserPriority=100 will be 100x less likely to be
	// aborted as conflicting transactions or non-transactional commands
	// with UserPriority=1. This value is ignored if Txn is
	// specified. If neither this value nor Txn is specified, the value
	// defaults to 1.
	UserPriority *int32 `protobuf:"varint,8,opt,name=user_priority,json=userPriority,def=1" json:"user_priority,omitempty"`
	// Txn is set non-nil if a transaction is underway. To start a txn,
	// the first request should set this field to non-nil with name and
	// isolation level set as desired. The response will contain the
	// fully-initialized transaction with txn ID, priority, initial
	// timestamp, and maximum timestamp.
	Txn                  *Transaction `protobuf:"bytes,9,opt,name=txn" json:"txn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

const Default_RequestHeader_UserPriority int32 = 1

func (m *RequestHeader) GetTimestamp() Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return Timestamp{}
}

func (m *RequestHeader) GetCmdID() ClientCmdID {
	if m != nil {
		return m.CmdID
	}
	return ClientCmdID{}
}

func (m *RequestHeader) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *RequestHeader) GetReplica() Replica {
	if m != nil {
		return m.Replica
	}
	return Replica{}
}

func (m *RequestHeader) GetRaftID() int64 {
	if m != nil {
		return m.RaftID
	}
	return 0
}

func (m *RequestHeader) GetUserPriority() int32 {
	if m != nil && m.UserPriority != nil {
		return *m.UserPriority
	}
	return Default_RequestHeader_UserPriority
}

func (m *RequestHeader) GetTxn() *Transaction {
	if m != nil {
		return m.Txn
	}
	return nil
}

// ResponseHeader is returned with every storage node response.
type ResponseHeader struct {
	// Error is non-nil if an error occurred.
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	// Timestamp specifies time at which read or write actually was
	// performed. In the case of both reads and writes, if the timestamp
	// supplied to the request was 0, the wall time of the node
	// servicing the request will be set here. Additionally, in the case
	// of writes, this value may be increased from the timestamp passed
	// with the RequestHeader if the key being written was either read
	// or written more recently.
	Timestamp Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp"`
	// Transaction is non-nil if the request specified a non-nil
	// transaction. The transaction timestamp and/or priority may have
	// been updated, depending on the outcome of the request.
	Txn                  *Transaction `protobuf:"bytes,3,opt,name=txn" json:"txn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}
func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ResponseHeader) GetTimestamp() Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return Timestamp{}
}

func (m *ResponseHeader) GetTxn() *Transaction {
	if m != nil {
		return m.Txn
	}
	return nil
}

// A ContainsRequest is arguments to the Contains() method.
type ContainsRequest struct {
	RequestHeader        `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainsRequest) Reset()         { *m = ContainsRequest{} }
func (m *ContainsRequest) String() string { return proto.CompactTextString(m) }
func (*ContainsRequest) ProtoMessage()    {}
func (*ContainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}
func (m *ContainsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainsRequest.Unmarshal(m, b)
}
func (m *ContainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainsRequest.Marshal(b, m, deterministic)
}
func (m *ContainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainsRequest.Merge(m, src)
}
func (m *ContainsRequest) XXX_Size() int {
	return xxx_messageInfo_ContainsRequest.Size(m)
}
func (m *ContainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainsRequest proto.InternalMessageInfo

// A ContainsResponse is the return value of the Contains() method.
type ContainsResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	Exists               bool     `protobuf:"varint,2,opt,name=exists" json:"exists"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainsResponse) Reset()         { *m = ContainsResponse{} }
func (m *ContainsResponse) String() string { return proto.CompactTextString(m) }
func (*ContainsResponse) ProtoMessage()    {}
func (*ContainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}
func (m *ContainsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainsResponse.Unmarshal(m, b)
}
func (m *ContainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainsResponse.Marshal(b, m, deterministic)
}
func (m *ContainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainsResponse.Merge(m, src)
}
func (m *ContainsResponse) XXX_Size() int {
	return xxx_messageInfo_ContainsResponse.Size(m)
}
func (m *ContainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainsResponse proto.InternalMessageInfo

func (m *ContainsResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

// A GetRequest is arguments to the Get() method.
type GetRequest struct {
	RequestHeader        `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

// A GetResponse is the return value from the Get() method.
// If the key doesn't exist, returns nil for Value.Bytes.
type GetResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	Value                *Value   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

// A PutRequest is arguments to the Put() method. Note that to write
// an empty value, the value parameter is still specified, but both
// Bytes and Integer are set to nil.
type PutRequest struct {
	RequestHeader        `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	Value                Value    `protobuf:"bytes,2,opt,name=value" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}
func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetValue() Value {
	if m != nil {
		return m.Value
	}
	return Value{}
}

// A PutResponse is the return value from the Put() method.
type PutResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}
func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

// A ConditionalPutRequest is arguments to the ConditionalPut() method.
//
// - Returns true and sets value if ExpValue equals existing value.
// - If key doesn't exist and ExpValue is nil, sets value.
// - If key exists, but value is empty and ExpValue is not nil but empty, sets value.
// - Otherwise, returns error and the actual value of the key in the response.
type ConditionalPutRequest struct {
	RequestHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	// The value to put.
	Value Value `protobuf:"bytes,2,opt,name=value" json:"value"`
	// ExpValue.Bytes empty to test for non-existence. Specify as nil
	// to indicate there should be no existing entry. This is different
	// from the expectation that the value exists but is empty.
	ExpValue             *Value   `protobuf:"bytes,3,opt,name=exp_value,json=expValue" json:"exp_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConditionalPutRequest) Reset()         { *m = ConditionalPutRequest{} }
func (m *ConditionalPutRequest) String() string { return proto.CompactTextString(m) }
func (*ConditionalPutRequest) ProtoMessage()    {}
func (*ConditionalPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}
func (m *ConditionalPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConditionalPutRequest.Unmarshal(m, b)
}
func (m *ConditionalPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConditionalPutRequest.Marshal(b, m, deterministic)
}
func (m *ConditionalPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConditionalPutRequest.Merge(m, src)
}
func (m *ConditionalPutRequest) XXX_Size() int {
	return xxx_messageInfo_ConditionalPutRequest.Size(m)
}
func (m *ConditionalPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConditionalPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConditionalPutRequest proto.InternalMessageInfo

func (m *ConditionalPutRequest) GetValue() Value {
	if m != nil {
		return m.Value
	}
	return Value{}
}

func (m *ConditionalPutRequest) GetExpValue() *Value {
	if m != nil {
		return m.ExpValue
	}
	return nil
}

// A ConditionalPutResponse is the return value from the
// ConditionalPut() method.
type ConditionalPutResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConditionalPutResponse) Reset()         { *m = ConditionalPutResponse{} }
func (m *ConditionalPutResponse) String() string { return proto.CompactTextString(m) }
func (*ConditionalPutResponse) ProtoMessage()    {}
func (*ConditionalPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}
func (m *ConditionalPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConditionalPutResponse.Unmarshal(m, b)
}
func (m *ConditionalPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConditionalPutResponse.Marshal(b, m, deterministic)
}
func (m *ConditionalPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConditionalPutResponse.Merge(m, src)
}
func (m *ConditionalPutResponse) XXX_Size() int {
	return xxx_messageInfo_ConditionalPutResponse.Size(m)
}
func (m *ConditionalPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConditionalPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConditionalPutResponse proto.InternalMessageInfo

// An IncrementRequest is arguments to the Increment() method. It
// increments the value for key, and returns the new value. If no
// value exists for a key, incrementing by 0 is not a noop, but will
// create a zero value. IncrementRequest cannot be called on a key set
// by Put() or ConditionalPut(). Similarly, Get(), Put() and
// ConditionalPut() cannot be invoked on an incremented key.
type IncrementRequest struct {
	RequestHeader        `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	Increment            int64    `protobuf:"varint,2,opt,name=increment" json:"increment"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrementRequest) Reset()         { *m = IncrementRequest{} }
func (m *IncrementRequest) String() string { return proto.CompactTextString(m) }
func (*IncrementRequest) ProtoMessage()    {}
func (*IncrementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}
func (m *IncrementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrementRequest.Unmarshal(m, b)
}
func (m *IncrementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrementRequest.Marshal(b, m, deterministic)
}
func (m *IncrementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrementRequest.Merge(m, src)
}
func (m *IncrementRequest) XXX_Size() int {
	return xxx_messageInfo_IncrementRequest.Size(m)
}
func (m *IncrementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncrementRequest proto.InternalMessageInfo

func (m *IncrementRequest) GetIncrement() int64 {
	if m != nil {
		return m.Increment
	}
	return 0
}

// An IncrementResponse is the return value from the Increment
// method. The new value after increment is specified in NewValue. If
// the value could not be decoded as specified, Error will be set.
type IncrementResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	NewValue             int64    `protobuf:"varint,2,opt,name=new_value,json=newValue" json:"new_value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrementResponse) Reset()         { *m = IncrementResponse{} }
func (m *IncrementResponse) String() string { return proto.CompactTextString(m) }
func (*IncrementResponse) ProtoMessage()    {}
func (*IncrementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}
func (m *IncrementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrementResponse.Unmarshal(m, b)
}
func (m *IncrementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrementResponse.Marshal(b, m, deterministic)
}
func (m *IncrementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrementResponse.Merge(m, src)
}
func (m *IncrementResponse) XXX_Size() int {
	return xxx_messageInfo_IncrementResponse.Size(m)
}
func (m *IncrementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncrementResponse proto.InternalMessageInfo

func (m *IncrementResponse) GetNewValue() int64 {
	if m != nil {
		return m.NewValue
	}
	return 0
}

// A DeleteRequest is arguments to the Delete() method.
type DeleteRequest struct {
	RequestHeader        `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

// A DeleteResponse is the return value from the Delete() method.
type DeleteResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

// A DeleteRangeRequest is arguments to the DeleteRange method. It
// specifies the range of keys to delete.
type DeleteRangeRequest struct {
	RequestHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	// If 0, *all* entries between Key (inclusive) and EndKey
	// (exclusive) are deleted. Must be >= 0
	MaxEntriesToDelete   int64    `protobuf:"varint,2,opt,name=max_entries_to_delete,json=maxEntriesToDelete" json:"max_entries_to_delete"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRangeRequest) Reset()         { *m = DeleteRangeRequest{} }
func (m *DeleteRangeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRangeRequest) ProtoMessage()    {}
func (*DeleteRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}
func (m *DeleteRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRangeRequest.Unmarshal(m, b)
}
func (m *DeleteRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRangeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRangeRequest.Merge(m, src)
}
func (m *DeleteRangeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRangeRequest.Size(m)
}
func (m *DeleteRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRangeRequest proto.InternalMessageInfo

func (m *DeleteRangeRequest) GetMaxEntriesToDelete() int64 {
	if m != nil {
		return m.MaxEntriesToDelete
	}
	return 0
}

// A DeleteRangeResponse is the return value from the DeleteRange()
// method.
type DeleteRangeResponse struct {
	ResponseHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	// Number of entries removed.
	NumDeleted           int64    `protobuf:"varint,2,opt,name=num_deleted,json=numDeleted" json:"num_deleted"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRangeResponse) Reset()         { *m = DeleteRangeResponse{} }
func (m *DeleteRangeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRangeResponse) ProtoMessage()    {}
func (*DeleteRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}
func (m *DeleteRangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRangeResponse.Unmarshal(m, b)
}
func (m *DeleteRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRangeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRangeResponse.Merge(m, src)
}
func (m *DeleteRangeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRangeResponse.Size(m)
}
func (m *DeleteRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRangeResponse proto.InternalMessageInfo

func (m *DeleteRangeResponse) GetNumDeleted() int64 {
	if m != nil {
		return m.NumDeleted
	}
	return 0
}

// A ScanRequest is arguments to the Scan() method. It specifies the
// start and end keys for the scan and the maximum number of results.
type ScanRequest struct {
	RequestHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	// Must be > 0.
	MaxResults           int64    `protobuf:"varint,2,opt,name=max_results,json=maxResults" json:"max_results"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}
func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetMaxResults() int64 {
	if m != nil {
		return m.MaxResults
	}
	return 0
}

// A ScanResponse is the return value from the Scan() method.
type ScanResponse struct {
	ResponseHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	// Empty if no rows were scanned.
	Rows                 []KeyValue `protobuf:"bytes,2,rep,name=rows" json:"rows"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}
func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetRows() []KeyValue {
	if m != nil {
		return m.Rows
	}
	return nil
}

// An EndTransactionRequest is arguments to the EndTransaction() method.
// It specifies whether to commit or roll back an extant transaction.
type EndTransactionRequest struct {
	RequestHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	// False to abort and rollback.
	Commit bool `protobuf:"varint,2,opt,name=commit" json:"commit"`
	// Optional commit triggers. Note that commit triggers are for
	// internal use only and will be ignored if requested through the
	// public-facing KV API.
	SplitTrigger         *SplitTrigger `protobuf:"bytes,3,opt,name=split_trigger,json=splitTrigger" json:"split_trigger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EndTransactionRequest) Reset()         { *m = EndTransactionRequest{} }
func (m *EndTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*EndTransactionRequest) ProtoMessage()    {}
func (*EndTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}
func (m *EndTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndTransactionRequest.Unmarshal(m, b)
}
func (m *EndTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndTransactionRequest.Marshal(b, m, deterministic)
}
func (m *EndTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndTransactionRequest.Merge(m, src)
}
func (m *EndTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_EndTransactionRequest.Size(m)
}
func (m *EndTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndTransactionRequest proto.InternalMessageInfo

func (m *EndTransactionRequest) GetCommit() bool {
	if m != nil {
		return m.Commit
	}
	return false
}

func (m *EndTransactionRequest) GetSplitTrigger() *SplitTrigger {
	if m != nil {
		return m.SplitTrigger
	}
	return nil
}

// An EndTransactionResponse is the return value from the
// EndTransaction() method. The final transaction record is returned
// as part of the response header. In particular, transaction status
// and timestamp will be updated to reflect final committed
// values. Clients may propagate the transaction timestamp as the
// final txn commit timestamp in order to preserve causal ordering
// between subsequent transactions. CommitWait specifies the commit
// wait, which is the remaining time the client MUST wait before
// signalling completion of the transaction to another distributed
// node to maintain consistency.
type EndTransactionResponse struct {
	ResponseHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	// Remaining time (ns).
	CommitWait           int64    `protobuf:"varint,2,opt,name=commit_wait,json=commitWait" json:"commit_wait"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndTransactionResponse) Reset()         { *m = EndTransactionResponse{} }
func (m *EndTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*EndTransactionResponse) ProtoMessage()    {}
func (*EndTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}
func (m *EndTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndTransactionResponse.Unmarshal(m, b)
}
func (m *EndTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndTransactionResponse.Marshal(b, m, deterministic)
}
func (m *EndTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndTransactionResponse.Merge(m, src)
}
func (m *EndTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_EndTransactionResponse.Size(m)
}
func (m *EndTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EndTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EndTransactionResponse proto.InternalMessageInfo

func (m *EndTransactionResponse) GetCommitWait() int64 {
	if m != nil {
		return m.CommitWait
	}
	return 0
}

// A ReapQueueRequest is arguments to the ReapQueue() method. It
// specifies the recipient inbox key to which messages are waiting
// to be reapted and also the maximum number of results to return.
type ReapQueueRequest struct {
	RequestHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	// Maximum results to return; must be > 0.
	MaxResults           int64    `protobuf:"varint,2,opt,name=max_results,json=maxResults" json:"max_results"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReapQueueRequest) Reset()         { *m = ReapQueueRequest{} }
func (m *ReapQueueRequest) String() string { return proto.CompactTextString(m) }
func (*ReapQueueRequest) ProtoMessage()    {}
func (*ReapQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}
func (m *ReapQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReapQueueRequest.Unmarshal(m, b)
}
func (m *ReapQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReapQueueRequest.Marshal(b, m, deterministic)
}
func (m *ReapQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReapQueueRequest.Merge(m, src)
}
func (m *ReapQueueRequest) XXX_Size() int {
	return xxx_messageInfo_ReapQueueRequest.Size(m)
}
func (m *ReapQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReapQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReapQueueRequest proto.InternalMessageInfo

func (m *ReapQueueRequest) GetMaxResults() int64 {
	if m != nil {
		return m.MaxResults
	}
	return 0
}

// A ReapQueueResponse is the return value from the ReapQueue() method.
type ReapQueueResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	Messages             []Value  `protobuf:"bytes,2,rep,name=messages" json:"messages"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReapQueueResponse) Reset()         { *m = ReapQueueResponse{} }
func (m *ReapQueueResponse) String() string { return proto.CompactTextString(m) }
func (*ReapQueueResponse) ProtoMessage()    {}
func (*ReapQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}
func (m *ReapQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReapQueueResponse.Unmarshal(m, b)
}
func (m *ReapQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReapQueueResponse.Marshal(b, m, deterministic)
}
func (m *ReapQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReapQueueResponse.Merge(m, src)
}
func (m *ReapQueueResponse) XXX_Size() int {
	return xxx_messageInfo_ReapQueueResponse.Size(m)
}
func (m *ReapQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReapQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReapQueueResponse proto.InternalMessageInfo

func (m *ReapQueueResponse) GetMessages() []Value {
	if m != nil {
		return m.Messages
	}
	return nil
}

// An EnqueueUpdateRequest is arguments to the EnqueueUpdate() method.
// It specifies the update to enqueue for asynchronous execution.
// Update is an instance of one of the following messages: PutRequest,
// IncrementRequest, DeleteRequest, DeleteRangeRequest, or
// AccountingRequest.
type EnqueueUpdateRequest struct {
	RequestHeader        `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnqueueUpdateRequest) Reset()         { *m = EnqueueUpdateRequest{} }
func (m *EnqueueUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*EnqueueUpdateRequest) ProtoMessage()    {}
func (*EnqueueUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}
func (m *EnqueueUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueUpdateRequest.Unmarshal(m, b)
}
func (m *EnqueueUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueUpdateRequest.Marshal(b, m, deterministic)
}
func (m *EnqueueUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueUpdateRequest.Merge(m, src)
}
func (m *EnqueueUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_EnqueueUpdateRequest.Size(m)
}
func (m *EnqueueUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueUpdateRequest proto.InternalMessageInfo

// An EnqueueUpdateResponse is the return value from the
// EnqueueUpdate() method.
type EnqueueUpdateResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnqueueUpdateResponse) Reset()         { *m = EnqueueUpdateResponse{} }
func (m *EnqueueUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*EnqueueUpdateResponse) ProtoMessage()    {}
func (*EnqueueUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{24}
}
func (m *EnqueueUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueUpdateResponse.Unmarshal(m, b)
}
func (m *EnqueueUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueUpdateResponse.Marshal(b, m, deterministic)
}
func (m *EnqueueUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueUpdateResponse.Merge(m, src)
}
func (m *EnqueueUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_EnqueueUpdateResponse.Size(m)
}
func (m *EnqueueUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueUpdateResponse proto.InternalMessageInfo

// An EnqueueMessageRequest is arguments to the EnqueueMessage() method.
// It specifies the recipient inbox key and the message (an arbitrary
// byte slice value).
type EnqueueMessageRequest struct {
	RequestHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	// Message value to delivery to inbox.
	Msg                  Value    `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnqueueMessageRequest) Reset()         { *m = EnqueueMessageRequest{} }
func (m *EnqueueMessageRequest) String() string { return proto.CompactTextString(m) }
func (*EnqueueMessageRequest) ProtoMessage()    {}
func (*EnqueueMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{25}
}
func (m *EnqueueMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueMessageRequest.Unmarshal(m, b)
}
func (m *EnqueueMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueMessageRequest.Marshal(b, m, deterministic)
}
func (m *EnqueueMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueMessageRequest.Merge(m, src)
}
func (m *EnqueueMessageRequest) XXX_Size() int {
	return xxx_messageInfo_EnqueueMessageRequest.Size(m)
}
func (m *EnqueueMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueMessageRequest proto.InternalMessageInfo

func (m *EnqueueMessageRequest) GetMsg() Value {
	if m != nil {
		return m.Msg
	}
	return Value{}
}

// An EnqueueMessageResponse is the return value from the
// EnqueueMessage() method.
type EnqueueMessageResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnqueueMessageResponse) Reset()         { *m = EnqueueMessageResponse{} }
func (m *EnqueueMessageResponse) String() string { return proto.CompactTextString(m) }
func (*EnqueueMessageResponse) ProtoMessage()    {}
func (*EnqueueMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{26}
}
func (m *EnqueueMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueMessageResponse.Unmarshal(m, b)
}
func (m *EnqueueMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueMessageResponse.Marshal(b, m, deterministic)
}
func (m *EnqueueMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueMessageResponse.Merge(m, src)
}
func (m *EnqueueMessageResponse) XXX_Size() int {
	return xxx_messageInfo_EnqueueMessageResponse.Size(m)
}
func (m *EnqueueMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueMessageResponse proto.InternalMessageInfo

// A RequestUnion contains exactly one of the optional requests.
type RequestUnion struct {
	Contains             *ContainsRequest       `protobuf:"bytes,1,opt,name=contains" json:"contains,omitempty"`
	Get                  *GetRequest            `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	Put                  *PutRequest            `protobuf:"bytes,3,opt,name=put" json:"put,omitempty"`
	ConditionalPut       *ConditionalPutRequest `protobuf:"bytes,4,opt,name=conditional_put,json=conditionalPut" json:"conditional_put,omitempty"`
	Increment            *IncrementRequest      `protobuf:"bytes,5,opt,name=increment" json:"increment,omitempty"`
	Delete               *DeleteRequest         `protobuf:"bytes,6,opt,name=delete" json:"delete,omitempty"`
	DeleteRange          *DeleteRangeRequest    `protobuf:"bytes,7,opt,name=delete_range,json=deleteRange" json:"delete_range,omitempty"`
	Scan                 *ScanRequest           `protobuf:"bytes,8,opt,name=scan" json:"scan,omitempty"`
	EndTransaction       *EndTransactionRequest `protobuf:"bytes,9,opt,name=end_transaction,json=endTransaction" json:"end_transaction,omitempty"`
	ReapQueue            *ReapQueueRequest      `protobuf:"bytes,10,opt,name=reap_queue,json=reapQueue" json:"reap_queue,omitempty"`
	EnqueueUpdate        *EnqueueUpdateRequest  `protobuf:"bytes,11,opt,name=enqueue_update,json=enqueueUpdate" json:"enqueue_update,omitempty"`
	EnqueueMessage       *EnqueueMessageRequest `protobuf:"bytes,12,opt,name=enqueue_message,json=enqueueMessage" json:"enqueue_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RequestUnion) Reset()         { *m = RequestUnion{} }
func (m *RequestUnion) String() string { return proto.CompactTextString(m) }
func (*RequestUnion) ProtoMessage()    {}
func (*RequestUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{27}
}
func (m *RequestUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUnion.Unmarshal(m, b)
}
func (m *RequestUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUnion.Marshal(b, m, deterministic)
}
func (m *RequestUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUnion.Merge(m, src)
}
func (m *RequestUnion) XXX_Size() int {
	return xxx_messageInfo_RequestUnion.Size(m)
}
func (m *RequestUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUnion.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUnion proto.InternalMessageInfo

func (m *RequestUnion) GetContains() *ContainsRequest {
	if m != nil {
		return m.Contains
	}
	return nil
}

func (m *RequestUnion) GetGet() *GetRequest {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *RequestUnion) GetPut() *PutRequest {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *RequestUnion) GetConditionalPut() *ConditionalPutRequest {
	if m != nil {
		return m.ConditionalPut
	}
	return nil
}

func (m *RequestUnion) GetIncrement() *IncrementRequest {
	if m != nil {
		return m.Increment
	}
	return nil
}

func (m *RequestUnion) GetDelete() *DeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *RequestUnion) GetDeleteRange() *DeleteRangeRequest {
	if m != nil {
		return m.DeleteRange
	}
	return nil
}

func (m *RequestUnion) GetScan() *ScanRequest {
	if m != nil {
		return m.Scan
	}
	return nil
}

func (m *RequestUnion) GetEndTransaction() *EndTransactionRequest {
	if m != nil {
		return m.EndTransaction
	}
	return nil
}

func (m *RequestUnion) GetReapQueue() *ReapQueueRequest {
	if m != nil {
		return m.ReapQueue
	}
	return nil
}

func (m *RequestUnion) GetEnqueueUpdate() *EnqueueUpdateRequest {
	if m != nil {
		return m.EnqueueUpdate
	}
	return nil
}

func (m *RequestUnion) GetEnqueueMessage() *EnqueueMessageRequest {
	if m != nil {
		return m.EnqueueMessage
	}
	return nil
}

// A ResponseUnion contains exactly one of the optional responses.
type ResponseUnion struct {
	Contains             *ContainsResponse       `protobuf:"bytes,1,opt,name=contains" json:"contains,omitempty"`
	Get                  *GetResponse            `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	Put                  *PutResponse            `protobuf:"bytes,3,opt,name=put" json:"put,omitempty"`
	ConditionalPut       *ConditionalPutResponse `protobuf:"bytes,4,opt,name=conditional_put,json=conditionalPut" json:"conditional_put,omitempty"`
	Increment            *IncrementResponse      `protobuf:"bytes,5,opt,name=increment" json:"increment,omitempty"`
	Delete               *DeleteResponse         `protobuf:"bytes,6,opt,name=delete" json:"delete,omitempty"`
	DeleteRange          *DeleteRangeResponse    `protobuf:"bytes,7,opt,name=delete_range,json=deleteRange" json:"delete_range,omitempty"`
	Scan                 *ScanResponse           `protobuf:"bytes,8,opt,name=scan" json:"scan,omitempty"`
	EndTransaction       *EndTransactionResponse `protobuf:"bytes,9,opt,name=end_transaction,json=endTransaction" json:"end_transaction,omitempty"`
	ReapQueue            *ReapQueueResponse      `protobuf:"bytes,10,opt,name=reap_queue,json=reapQueue" json:"reap_queue,omitempty"`
	EnqueueUpdate        *EnqueueUpdateResponse  `protobuf:"bytes,11,opt,name=enqueue_update,json=enqueueUpdate" json:"enqueue_update,omitempty"`
	EnqueueMessage       *EnqueueMessageResponse `protobuf:"bytes,12,opt,name=enqueue_message,json=enqueueMessage" json:"enqueue_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ResponseUnion) Reset()         { *m = ResponseUnion{} }
func (m *ResponseUnion) String() string { return proto.CompactTextString(m) }
func (*ResponseUnion) ProtoMessage()    {}
func (*ResponseUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{28}
}
func (m *ResponseUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUnion.Unmarshal(m, b)
}
func (m *ResponseUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUnion.Marshal(b, m, deterministic)
}
func (m *ResponseUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUnion.Merge(m, src)
}
func (m *ResponseUnion) XXX_Size() int {
	return xxx_messageInfo_ResponseUnion.Size(m)
}
func (m *ResponseUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUnion.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUnion proto.InternalMessageInfo

func (m *ResponseUnion) GetContains() *ContainsResponse {
	if m != nil {
		return m.Contains
	}
	return nil
}

func (m *ResponseUnion) GetGet() *GetResponse {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *ResponseUnion) GetPut() *PutResponse {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *ResponseUnion) GetConditionalPut() *ConditionalPutResponse {
	if m != nil {
		return m.ConditionalPut
	}
	return nil
}

func (m *ResponseUnion) GetIncrement() *IncrementResponse {
	if m != nil {
		return m.Increment
	}
	return nil
}

func (m *ResponseUnion) GetDelete() *DeleteResponse {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *ResponseUnion) GetDeleteRange() *DeleteRangeResponse {
	if m != nil {
		return m.DeleteRange
	}
	return nil
}

func (m *ResponseUnion) GetScan() *ScanResponse {
	if m != nil {
		return m.Scan
	}
	return nil
}

func (m *ResponseUnion) GetEndTransaction() *EndTransactionResponse {
	if m != nil {
		return m.EndTransaction
	}
	return nil
}

func (m *ResponseUnion) GetReapQueue() *ReapQueueResponse {
	if m != nil {
		return m.ReapQueue
	}
	return nil
}

func (m *ResponseUnion) GetEnqueueUpdate() *EnqueueUpdateResponse {
	if m != nil {
		return m.EnqueueUpdate
	}
	return nil
}

func (m *ResponseUnion) GetEnqueueMessage() *EnqueueMessageResponse {
	if m != nil {
		return m.EnqueueMessage
	}
	return nil
}

// A BatchRequest contains one or more requests to be executed in
// parallel, or if applicable (based on write-only commands and
// range-locality), as a single update.
type BatchRequest struct {
	RequestHeader        `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	Requests             []RequestUnion `protobuf:"bytes,2,rep,name=requests" json:"requests"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BatchRequest) Reset()         { *m = BatchRequest{} }
func (m *BatchRequest) String() string { return proto.CompactTextString(m) }
func (*BatchRequest) ProtoMessage()    {}
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{29}
}
func (m *BatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchRequest.Unmarshal(m, b)
}
func (m *BatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchRequest.Marshal(b, m, deterministic)
}
func (m *BatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchRequest.Merge(m, src)
}
func (m *BatchRequest) XXX_Size() int {
	return xxx_messageInfo_BatchRequest.Size(m)
}
func (m *BatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchRequest proto.InternalMessageInfo

func (m *BatchRequest) GetRequests() []RequestUnion {
	if m != nil {
		return m.Requests
	}
	return nil
}

// A BatchResponse contains one or more responses, one per request
// corresponding to the requests in the matching BatchRequest. The
// error in the response header is set to the first error from the
// slice of responses, if applicable.
type BatchResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	Responses            []ResponseUnion `protobuf:"bytes,2,rep,name=responses" json:"responses"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BatchResponse) Reset()         { *m = BatchResponse{} }
func (m *BatchResponse) String() string { return proto.CompactTextString(m) }
func (*BatchResponse) ProtoMessage()    {}
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{30}
}
func (m *BatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchResponse.Unmarshal(m, b)
}
func (m *BatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchResponse.Marshal(b, m, deterministic)
}
func (m *BatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchResponse.Merge(m, src)
}
func (m *BatchResponse) XXX_Size() int {
	return xxx_messageInfo_BatchResponse.Size(m)
}
func (m *BatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchResponse proto.InternalMessageInfo

func (m *BatchResponse) GetResponses() []ResponseUnion {
	if m != nil {
		return m.Responses
	}
	return nil
}

// An AdminSplitRequest is arguments to the AdminSplit() method. The
// existing range which contains RequestHeader.Key is split by
// split_key. If split_key is not specified, then this method will
// determine a split key that is roughly halfway through the
// range. The existing range is resized to cover only its start key to
// the split key. The new range created by the split starts at the
// split key and extends to the original range's end key. If split_key
// is known, header.key should also be set to split_key.
//
// New range IDs for each of the split range's replica and a new Raft
// ID are generated by the operation. Split requests are done in the
// context of a distributed transaction which updates range addressing
// records, range metadata and finally, provides a commit trigger to
// update bookkeeping and instantiate the new range on commit.
//
// The new range contains range replicas located on the same stores;
// no range data is moved during this operation. The split can be
// thought of as a mostly logical operation, though some other
// metadata (e.g. response cache and range stats must be copied or
// recomputed).
type AdminSplitRequest struct {
	RequestHeader        `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	SplitKey             Key      `protobuf:"bytes,2,opt,name=split_key,json=splitKey,customtype=Key" json:"split_key"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminSplitRequest) Reset()         { *m = AdminSplitRequest{} }
func (m *AdminSplitRequest) String() string { return proto.CompactTextString(m) }
func (*AdminSplitRequest) ProtoMessage()    {}
func (*AdminSplitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{31}
}
func (m *AdminSplitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminSplitRequest.Unmarshal(m, b)
}
func (m *AdminSplitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminSplitRequest.Marshal(b, m, deterministic)
}
func (m *AdminSplitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminSplitRequest.Merge(m, src)
}
func (m *AdminSplitRequest) XXX_Size() int {
	return xxx_messageInfo_AdminSplitRequest.Size(m)
}
func (m *AdminSplitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminSplitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminSplitRequest proto.InternalMessageInfo

// An AdminSplitResponse is the return value from the AdminSplit()
// method.
type AdminSplitResponse struct {
	ResponseHeader       `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminSplitResponse) Reset()         { *m = AdminSplitResponse{} }
func (m *AdminSplitResponse) String() string { return proto.CompactTextString(m) }
func (*AdminSplitResponse) ProtoMessage()    {}
func (*AdminSplitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{32}
}
func (m *AdminSplitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminSplitResponse.Unmarshal(m, b)
}
func (m *AdminSplitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminSplitResponse.Marshal(b, m, deterministic)
}
func (m *AdminSplitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminSplitResponse.Merge(m, src)
}
func (m *AdminSplitResponse) XXX_Size() int {
	return xxx_messageInfo_AdminSplitResponse.Size(m)
}
func (m *AdminSplitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminSplitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminSplitResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientCmdID)(nil), "proto.ClientCmdID")
	proto.RegisterType((*RequestHeader)(nil), "proto.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "proto.ResponseHeader")
	proto.RegisterType((*ContainsRequest)(nil), "proto.ContainsRequest")
	proto.RegisterType((*ContainsResponse)(nil), "proto.ContainsResponse")
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "proto.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "proto.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "proto.PutResponse")
	proto.RegisterType((*ConditionalPutRequest)(nil), "proto.ConditionalPutRequest")
	proto.RegisterType((*ConditionalPutResponse)(nil), "proto.ConditionalPutResponse")
	proto.RegisterType((*IncrementRequest)(nil), "proto.IncrementRequest")
	proto.RegisterType((*IncrementResponse)(nil), "proto.IncrementResponse")
	proto.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
	proto.RegisterType((*DeleteRangeRequest)(nil), "proto.DeleteRangeRequest")
	proto.RegisterType((*DeleteRangeResponse)(nil), "proto.DeleteRangeResponse")
	proto.RegisterType((*ScanRequest)(nil), "proto.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "proto.ScanResponse")
	proto.RegisterType((*EndTransactionRequest)(nil), "proto.EndTransactionRequest")
	proto.RegisterType((*EndTransactionResponse)(nil), "proto.EndTransactionResponse")
	proto.RegisterType((*ReapQueueRequest)(nil), "proto.ReapQueueRequest")
	proto.RegisterType((*ReapQueueResponse)(nil), "proto.ReapQueueResponse")
	proto.RegisterType((*EnqueueUpdateRequest)(nil), "proto.EnqueueUpdateRequest")
	proto.RegisterType((*EnqueueUpdateResponse)(nil), "proto.EnqueueUpdateResponse")
	proto.RegisterType((*EnqueueMessageRequest)(nil), "proto.EnqueueMessageRequest")
	proto.RegisterType((*EnqueueMessageResponse)(nil), "proto.EnqueueMessageResponse")
	proto.RegisterType((*RequestUnion)(nil), "proto.RequestUnion")
	proto.RegisterType((*ResponseUnion)(nil), "proto.ResponseUnion")
	proto.RegisterType((*BatchRequest)(nil), "proto.BatchRequest")
	proto.RegisterType((*BatchResponse)(nil), "proto.BatchResponse")
	proto.RegisterType((*AdminSplitRequest)(nil), "proto.AdminSplitRequest")
	proto.RegisterType((*AdminSplitResponse)(nil), "proto.AdminSplitResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x98, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0x80, 0x7f, 0x45, 0x96, 0x2c, 0x1d, 0x4a, 0x8a, 0x3d, 0x8e, 0x13, 0xfe, 0xa9, 0x0d, 0x3b,
	0xac, 0x93, 0x38, 0x40, 0xe3, 0xa0, 0x6e, 0x73, 0x41, 0xd0, 0x2e, 0xea, 0x5b, 0x2a, 0x18, 0x09,
	0x92, 0x89, 0xd3, 0x2e, 0x89, 0x09, 0x39, 0x56, 0xd8, 0x88, 0x43, 0x86, 0x1c, 0xd6, 0x12, 0xd0,
	0x6e, 0x0a, 0x64, 0xdf, 0x47, 0xe8, 0xa2, 0x40, 0x77, 0x7d, 0x81, 0xbe, 0x40, 0x96, 0x5d, 0x77,
	0xe1, 0x45, 0x9f, 0xa4, 0x98, 0x0b, 0xc5, 0x8b, 0xa4, 0xa0, 0x00, 0x8b, 0xac, 0x2c, 0x9e, 0x39,
	0x73, 0x6e, 0xf3, 0xcd, 0x9c, 0x19, 0x43, 0x9b, 0x84, 0xde, 0x4e, 0x18, 0x05, 0x3c, 0x40, 0x0d,
	0xf9, 0xe7, 0x6a, 0xc7, 0x09, 0xd8, 0xa9, 0x37, 0x50, 0xc2, 0xab, 0xe0, 0x12, 0x4e, 0xf4, 0xef,
	0x0e, 0x8d, 0xa2, 0x20, 0x8a, 0xf5, 0xd7, 0xed, 0x81, 0xc7, 0x5f, 0x25, 0x2f, 0x77, 0x9c, 0xc0,
	0xbf, 0x33, 0x08, 0x06, 0xc1, 0x1d, 0x29, 0x7e, 0x99, 0x9c, 0xca, 0x2f, 0xf9, 0x21, 0x7f, 0x29,
	0x75, 0xeb, 0x09, 0x18, 0xfb, 0x43, 0x8f, 0x32, 0xbe, 0xef, 0xbb, 0xfd, 0x03, 0x74, 0x0d, 0xda,
	0x67, 0x64, 0x38, 0xb4, 0xb9, 0xe7, 0x53, 0xb3, 0xb6, 0x59, 0xdb, 0xae, 0xef, 0x2d, 0xbc, 0x3b,
	0xdf, 0xf8, 0x1f, 0x6e, 0x09, 0xf1, 0x89, 0xe7, 0x53, 0xb4, 0x06, 0xcd, 0x88, 0x30, 0x37, 0xf0,
	0xcd, 0x0b, 0xb9, 0x71, 0x2d, 0xb3, 0xde, 0xd6, 0xa1, 0x8b, 0xe9, 0x9b, 0x84, 0xc6, 0xfc, 0x6b,
	0x4a, 0x5c, 0x1a, 0xa1, 0xcf, 0xa1, 0x2d, 0xac, 0xc5, 0x9c, 0xf8, 0xa1, 0x34, 0x69, 0xec, 0x2e,
	0x29, 0xe7, 0x3b, 0x27, 0xa9, 0x5c, 0x1b, 0xc9, 0x14, 0xd1, 0x03, 0x68, 0x3a, 0xbe, 0x6b, 0x7b,
	0xae, 0xf4, 0x62, 0xec, 0x22, 0x3d, 0x25, 0x17, 0xec, 0x5e, 0x57, 0x4c, 0xfa, 0xfb, 0x7c, 0xa3,
	0x21, 0x3f, 0x71, 0xc3, 0xf1, 0xdd, 0xbe, 0x8b, 0xd6, 0xa1, 0xfe, 0x9a, 0x8e, 0xcd, 0xfa, 0x66,
	0x6d, 0xbb, 0xb3, 0x67, 0x08, 0x95, 0xbf, 0xce, 0x37, 0xea, 0xc7, 0x74, 0x8c, 0x85, 0x1c, 0x6d,
	0xc1, 0x22, 0x65, 0xae, 0x2d, 0x54, 0x16, 0xa6, 0x55, 0x9a, 0x94, 0xb9, 0xc7, 0x74, 0x8c, 0x4c,
	0x58, 0x48, 0x62, 0x1a, 0x99, 0x8d, 0xcd, 0xda, 0x76, 0x5b, 0x47, 0x27, 0x25, 0x68, 0x07, 0x16,
	0x23, 0x1a, 0x0e, 0x3d, 0x87, 0x98, 0x4d, 0x19, 0x59, 0x4f, 0x47, 0x86, 0x95, 0x54, 0x2b, 0xa7,
	0x4a, 0xe8, 0x26, 0x2c, 0x46, 0xe4, 0x94, 0x8b, 0x4c, 0x16, 0x65, 0xbd, 0x7a, 0x3a, 0xea, 0x26,
	0x26, 0xa7, 0xbc, 0x7f, 0x20, 0x2a, 0x77, 0xca, 0xfb, 0x2e, 0xba, 0x01, 0x5d, 0xe1, 0xc0, 0x0e,
	0x23, 0x2f, 0x88, 0x3c, 0x3e, 0x36, 0x5b, 0x9b, 0xb5, 0xed, 0xc6, 0xc3, 0xda, 0xa7, 0xb8, 0x23,
	0xe4, 0x4f, 0xb5, 0x18, 0x6d, 0x41, 0x9d, 0x8f, 0x98, 0xd9, 0x2e, 0x94, 0xe5, 0x24, 0x22, 0x2c,
	0x26, 0x0e, 0xf7, 0x02, 0x86, 0xc5, 0xb0, 0xf5, 0x73, 0x0d, 0x7a, 0x98, 0xc6, 0x61, 0xc0, 0x62,
	0xaa, 0x17, 0xc2, 0x82, 0x86, 0x24, 0x45, 0x2f, 0x42, 0x47, 0x4f, 0x3d, 0x14, 0x32, 0xac, 0x86,
	0x8a, 0x8b, 0x75, 0xe1, 0xdf, 0x2e, 0x96, 0x0e, 0xa9, 0xfe, 0xfe, 0x90, 0xfa, 0x70, 0x71, 0x3f,
	0x60, 0x9c, 0x78, 0x2c, 0xd6, 0x84, 0xa0, 0x7b, 0xd0, 0x7c, 0x25, 0x83, 0xd3, 0x31, 0x5d, 0x9a,
	0xd4, 0x32, 0x47, 0xd0, 0x5e, 0x4b, 0xf8, 0xfb, 0xf3, 0x7c, 0xa3, 0x86, 0xb5, 0xb6, 0xe5, 0xc1,
	0x52, 0x66, 0x4a, 0x25, 0x89, 0xee, 0x97, 0x6c, 0xad, 0x4e, 0x6c, 0xe5, 0xab, 0x30, 0x6d, 0x4c,
	0x00, 0x4d, 0x47, 0x5e, 0xcc, 0x63, 0x99, 0x70, 0x2b, 0x05, 0x5a, 0xc9, 0xac, 0x03, 0x80, 0x47,
	0x94, 0x57, 0x0d, 0xf8, 0x3b, 0x30, 0xa4, 0x95, 0xaa, 0xb1, 0x5a, 0xd0, 0xf8, 0x9e, 0x0c, 0x13,
	0xaa, 0xd7, 0x26, 0x5d, 0xc3, 0x6f, 0x84, 0x0c, 0xab, 0x21, 0x8b, 0x01, 0x3c, 0x4d, 0xaa, 0x46,
	0x8c, 0xb6, 0xdf, 0xe3, 0x49, 0x97, 0x48, 0xfb, 0x3b, 0x02, 0x43, 0xfa, 0xab, 0x98, 0x9b, 0xf5,
	0x6b, 0x0d, 0x56, 0xf7, 0x03, 0xe6, 0x7a, 0x02, 0x19, 0x32, 0xfc, 0x90, 0x39, 0xa0, 0x5b, 0xd0,
	0xa6, 0xa3, 0xd0, 0x56, 0xda, 0xf5, 0x19, 0xb5, 0x6d, 0xd1, 0x51, 0x28, 0x7f, 0x59, 0xcf, 0xe0,
	0x72, 0x39, 0xca, 0xaa, 0x99, 0x33, 0x58, 0xea, 0x33, 0x27, 0xa2, 0x3e, 0x65, 0x95, 0x73, 0xb6,
	0xa0, 0xed, 0xa5, 0xb6, 0x0a, 0x27, 0x74, 0x26, 0xb6, 0x02, 0x58, 0xce, 0xf9, 0xab, 0xca, 0xe4,
	0x35, 0x68, 0x33, 0x7a, 0x66, 0x67, 0x95, 0x9e, 0xf4, 0x0c, 0x46, 0xcf, 0x54, 0xcd, 0x1e, 0x41,
	0xf7, 0x80, 0x0e, 0x29, 0xa7, 0x55, 0xf7, 0x51, 0x1f, 0x7a, 0xa9, 0xa1, 0xaa, 0x45, 0x7f, 0x5b,
	0x03, 0xa4, 0x6d, 0x11, 0x36, 0xa8, 0x1a, 0x19, 0xba, 0x0f, 0xab, 0x3e, 0x19, 0xd9, 0x94, 0xf1,
	0xc8, 0xa3, 0xb1, 0xcd, 0x03, 0xdb, 0x95, 0xc6, 0x0b, 0x15, 0x41, 0x3e, 0x19, 0x1d, 0x2a, 0x8d,
	0x93, 0x40, 0x39, 0xb7, 0x12, 0x58, 0x29, 0x84, 0x51, 0x75, 0x39, 0xae, 0x83, 0xc1, 0x12, 0x5f,
	0x7b, 0x77, 0x0b, 0xee, 0x81, 0x25, 0xbe, 0xf2, 0xe5, 0x5a, 0x43, 0x30, 0x9e, 0x3b, 0x84, 0x55,
	0x4d, 0xfb, 0x3a, 0x18, 0x22, 0xed, 0x88, 0xc6, 0xc9, 0x50, 0x9f, 0xa0, 0x13, 0x6f, 0x3e, 0x19,
	0x61, 0x25, 0xb7, 0x22, 0xe8, 0x28, 0x6f, 0x55, 0xb3, 0xbb, 0x05, 0x0b, 0x51, 0x70, 0x26, 0x1c,
	0xd5, 0xb7, 0x8d, 0xdd, 0x8b, 0x7a, 0xda, 0x31, 0x1d, 0xe7, 0x37, 0xb5, 0x54, 0xb1, 0x7e, 0xab,
	0xc1, 0xea, 0x21, 0x73, 0xf3, 0x7d, 0xa8, 0x62, 0xb2, 0x6b, 0xd0, 0x74, 0x02, 0xdf, 0xf7, 0x78,
	0xb1, 0x53, 0x28, 0x19, 0x7a, 0x00, 0xdd, 0x38, 0x1c, 0x7a, 0xdc, 0xe6, 0x91, 0x37, 0x18, 0xd0,
	0x48, 0x9f, 0x23, 0x2b, 0xda, 0xf8, 0x73, 0x31, 0x76, 0xa2, 0x86, 0x70, 0x27, 0xce, 0x7d, 0x59,
	0x23, 0xb8, 0x5c, 0x0e, 0xf4, 0x3f, 0xa0, 0x40, 0x85, 0x65, 0x9f, 0x11, 0xaf, 0x78, 0x10, 0x80,
	0x1a, 0xf8, 0x96, 0x78, 0xdc, 0x7a, 0x03, 0x4b, 0x98, 0x92, 0xf0, 0x59, 0x42, 0x13, 0xfa, 0x81,
	0x50, 0xf8, 0x01, 0x96, 0x73, 0x2e, 0xab, 0xe6, 0xb9, 0x03, 0x2d, 0x9f, 0xc6, 0x31, 0x19, 0xd0,
	0x94, 0x89, 0x59, 0xa7, 0xfc, 0x44, 0xc7, 0x7a, 0x02, 0x97, 0x0e, 0xd9, 0x1b, 0xe1, 0xfb, 0x45,
	0xe8, 0x92, 0xea, 0x07, 0xd2, 0x53, 0xc1, 0x58, 0xc1, 0x5e, 0xd5, 0x73, 0x29, 0x99, 0x58, 0x7c,
	0xac, 0x82, 0xae, 0xba, 0x2e, 0x5b, 0x50, 0xf7, 0xe3, 0xc1, 0x7b, 0x7a, 0xa0, 0x18, 0x16, 0x6d,
	0xad, 0xec, 0xb6, 0x6a, 0x26, 0xbf, 0x37, 0xa0, 0xa3, 0x83, 0x7b, 0xc1, 0xbc, 0x80, 0xa1, 0x5d,
	0x68, 0x39, 0xfa, 0xda, 0xa6, 0x6d, 0x5d, 0x4e, 0xaf, 0xf5, 0xc5, 0x8b, 0x21, 0x9e, 0xe8, 0xa1,
	0x8f, 0xa1, 0x3e, 0xa0, 0x5c, 0x47, 0xbf, 0xac, 0xd5, 0xb3, 0x1b, 0x19, 0x16, 0xa3, 0x42, 0x29,
	0x4c, 0xb8, 0xde, 0x70, 0xa9, 0x52, 0x76, 0x81, 0xc0, 0x62, 0x14, 0x1d, 0xc2, 0x45, 0x27, 0x6b,
	0xdc, 0xb6, 0x98, 0xb0, 0x20, 0x27, 0xac, 0x65, 0x41, 0x4c, 0x5f, 0x3e, 0x70, 0xcf, 0x29, 0x88,
	0xd1, 0xdd, 0x7c, 0x83, 0x6d, 0x48, 0x03, 0x57, 0xb4, 0x81, 0x72, 0x13, 0xcf, 0xf5, 0x5c, 0xf4,
	0x09, 0x34, 0x75, 0x43, 0x68, 0x16, 0x56, 0xaf, 0xd0, 0x17, 0xb1, 0xd6, 0x41, 0x5f, 0x40, 0x47,
	0xfd, 0xb2, 0x23, 0xd1, 0x15, 0xe4, 0xd3, 0xc1, 0xd8, 0xfd, 0x7f, 0x71, 0x4e, 0xae, 0x6d, 0x61,
	0xc3, 0xcd, 0x64, 0xe8, 0x06, 0x2c, 0xc4, 0x0e, 0x61, 0xf2, 0x05, 0x91, 0x5d, 0xc8, 0x73, 0xc7,
	0x3d, 0x96, 0xe3, 0xa2, 0x22, 0xe2, 0x2d, 0xc4, 0xb3, 0x83, 0x47, 0x3f, 0x2b, 0xd2, 0x8a, 0xcc,
	0x3c, 0x3e, 0x71, 0x8f, 0x16, 0xc4, 0xe8, 0x1e, 0x40, 0x44, 0x49, 0x68, 0x4b, 0x7a, 0x4c, 0x28,
	0x94, 0xa4, 0x7c, 0xba, 0xe0, 0x76, 0x94, 0x4a, 0xd0, 0x1e, 0xf4, 0xa8, 0x42, 0xce, 0x4e, 0xe4,
	0xe6, 0x31, 0x0d, 0x39, 0xf7, 0xa3, 0x89, 0xf7, 0xe9, 0x8d, 0x8a, 0xbb, 0x34, 0x2f, 0x55, 0x29,
	0x28, 0x1b, 0x7a, 0x8f, 0x9b, 0x9d, 0x52, 0x0a, 0x33, 0xf6, 0x12, 0x4e, 0x1d, 0x6b, 0xf1, 0xc3,
	0x85, 0x77, 0xbf, 0x6c, 0xd4, 0xac, 0x3f, 0x1a, 0xe2, 0xf1, 0xaa, 0xa8, 0x56, 0xc4, 0x7e, 0x36,
	0x45, 0xec, 0x95, 0x29, 0x62, 0x95, 0x7e, 0x0e, 0xd9, 0xad, 0x3c, 0xb2, 0x28, 0x8f, 0xac, 0x56,
	0x95, 0xcc, 0x6e, 0xe5, 0x99, 0x45, 0x79, 0x66, 0x53, 0x2d, 0x01, 0xed, 0xd1, 0x3c, 0x68, 0xd7,
	0xe7, 0x40, 0xab, 0x27, 0x97, 0xa9, 0xbd, 0x37, 0x4d, 0xad, 0x39, 0x4d, 0xad, 0x9e, 0x9c, 0xc3,
	0xf6, 0x76, 0x09, 0xdb, 0xd5, 0x12, 0xb6, 0x7a, 0x46, 0xca, 0xed, 0x97, 0x33, 0xb9, 0xbd, 0x3a,
	0x8b, 0x5b, 0x3d, 0xb3, 0x00, 0xee, 0xcd, 0x02, 0xb8, 0x2b, 0x05, 0x70, 0xb5, 0xbe, 0x22, 0xf7,
	0x68, 0x1e, 0xb9, 0xeb, 0x73, 0xc8, 0x4d, 0xcb, 0x52, 0x42, 0xf7, 0xfe, 0x0c, 0x74, 0xcd, 0x69,
	0x74, 0xd3, 0xba, 0x64, 0xec, 0xee, 0xcf, 0x61, 0x77, 0x6d, 0x36, 0xbb, 0xda, 0x40, 0x09, 0xde,
	0xa3, 0x79, 0xf0, 0xae, 0xcf, 0x81, 0x37, 0xcb, 0x62, 0x06, 0xbd, 0x3f, 0x42, 0x67, 0x8f, 0x70,
	0xe7, 0x55, 0xd5, 0x7e, 0x71, 0x17, 0x5a, 0x91, 0x52, 0x49, 0x5b, 0xea, 0x4a, 0x71, 0xa6, 0xdc,
	0x1a, 0x69, 0x67, 0x4d, 0x55, 0xad, 0x9f, 0x6a, 0xd0, 0xd5, 0xfe, 0xab, 0x36, 0xf5, 0x07, 0xd0,
	0x8e, 0xb4, 0x4e, 0x1a, 0xc2, 0xa5, 0xd2, 0xdc, 0x7c, 0x0c, 0x99, 0xb2, 0x95, 0xc0, 0xf2, 0x57,
	0xae, 0xef, 0x31, 0x79, 0xd9, 0xaa, 0xfe, 0x7c, 0x6c, 0xab, 0x0b, 0xdd, 0x6b, 0x3a, 0x96, 0xbb,
	0xb9, 0xf4, 0xcf, 0xa2, 0x96, 0x1c, 0x3d, 0xa6, 0x63, 0xeb, 0x31, 0xa0, 0xbc, 0xdb, 0x8a, 0xf9,
	0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xe2, 0x23, 0x58, 0xfe, 0x13, 0x00, 0x00,
}

func (this *RequestUnion) GetValue() interface{} {
	if this.Contains != nil {
		return this.Contains
	}
	if this.Get != nil {
		return this.Get
	}
	if this.Put != nil {
		return this.Put
	}
	if this.ConditionalPut != nil {
		return this.ConditionalPut
	}
	if this.Increment != nil {
		return this.Increment
	}
	if this.Delete != nil {
		return this.Delete
	}
	if this.DeleteRange != nil {
		return this.DeleteRange
	}
	if this.Scan != nil {
		return this.Scan
	}
	if this.EndTransaction != nil {
		return this.EndTransaction
	}
	if this.ReapQueue != nil {
		return this.ReapQueue
	}
	if this.EnqueueUpdate != nil {
		return this.EnqueueUpdate
	}
	if this.EnqueueMessage != nil {
		return this.EnqueueMessage
	}
	return nil
}

func (this *RequestUnion) SetValue(value interface{}) bool {
	switch vt := value.(type) {
	case *ContainsRequest:
		this.Contains = vt
	case *GetRequest:
		this.Get = vt
	case *PutRequest:
		this.Put = vt
	case *ConditionalPutRequest:
		this.ConditionalPut = vt
	case *IncrementRequest:
		this.Increment = vt
	case *DeleteRequest:
		this.Delete = vt
	case *DeleteRangeRequest:
		this.DeleteRange = vt
	case *ScanRequest:
		this.Scan = vt
	case *EndTransactionRequest:
		this.EndTransaction = vt
	case *ReapQueueRequest:
		this.ReapQueue = vt
	case *EnqueueUpdateRequest:
		this.EnqueueUpdate = vt
	case *EnqueueMessageRequest:
		this.EnqueueMessage = vt
	default:
		return false
	}
	return true
}
func (this *ResponseUnion) GetValue() interface{} {
	if this.Contains != nil {
		return this.Contains
	}
	if this.Get != nil {
		return this.Get
	}
	if this.Put != nil {
		return this.Put
	}
	if this.ConditionalPut != nil {
		return this.ConditionalPut
	}
	if this.Increment != nil {
		return this.Increment
	}
	if this.Delete != nil {
		return this.Delete
	}
	if this.DeleteRange != nil {
		return this.DeleteRange
	}
	if this.Scan != nil {
		return this.Scan
	}
	if this.EndTransaction != nil {
		return this.EndTransaction
	}
	if this.ReapQueue != nil {
		return this.ReapQueue
	}
	if this.EnqueueUpdate != nil {
		return this.EnqueueUpdate
	}
	if this.EnqueueMessage != nil {
		return this.EnqueueMessage
	}
	return nil
}

func (this *ResponseUnion) SetValue(value interface{}) bool {
	switch vt := value.(type) {
	case *ContainsResponse:
		this.Contains = vt
	case *GetResponse:
		this.Get = vt
	case *PutResponse:
		this.Put = vt
	case *ConditionalPutResponse:
		this.ConditionalPut = vt
	case *IncrementResponse:
		this.Increment = vt
	case *DeleteResponse:
		this.Delete = vt
	case *DeleteRangeResponse:
		this.DeleteRange = vt
	case *ScanResponse:
		this.Scan = vt
	case *EndTransactionResponse:
		this.EndTransaction = vt
	case *ReapQueueResponse:
		this.ReapQueue = vt
	case *EnqueueUpdateResponse:
		this.EnqueueUpdate = vt
	case *EnqueueMessageResponse:
		this.EnqueueMessage = vt
	default:
		return false
	}
	return true
}
