// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: heartbeat.proto

package proto

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RemoteOffset keeps track of this client's estimate of its offset from a
// remote server. Error is the maximum error in the reading of this offset, so
// that the real offset should be in the interval [Offset - Error, Offset
// + Error]. If the last heartbeat timed out, Offset = InfiniteOffset.
//
// Offset and error are measured using the remote clock reading technique
// described in http://se.inf.tu-dresden.de/pubs/papers/SRDS1994.pdf, page 6.
type RemoteOffset struct {
	// The estimated offset from the remote server, in nanoseconds.
	Offset int64 `protobuf:"varint,1,opt,name=offset" json:"offset"`
	// The maximum error of the measured offset, in nanoseconds.
	Error int64 `protobuf:"varint,2,opt,name=error" json:"error"`
	// Measurement time, in nanoseconds from unix epoch.
	MeasuredAt           int64    `protobuf:"varint,3,opt,name=measured_at,json=measuredAt" json:"measured_at"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteOffset) Reset()         { *m = RemoteOffset{} }
func (m *RemoteOffset) String() string { return proto.CompactTextString(m) }
func (*RemoteOffset) ProtoMessage()    {}
func (*RemoteOffset) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{0}
}
func (m *RemoteOffset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteOffset.Unmarshal(m, b)
}
func (m *RemoteOffset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteOffset.Marshal(b, m, deterministic)
}
func (m *RemoteOffset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteOffset.Merge(m, src)
}
func (m *RemoteOffset) XXX_Size() int {
	return xxx_messageInfo_RemoteOffset.Size(m)
}
func (m *RemoteOffset) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteOffset.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteOffset proto.InternalMessageInfo

func (m *RemoteOffset) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RemoteOffset) GetError() int64 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *RemoteOffset) GetMeasuredAt() int64 {
	if m != nil {
		return m.MeasuredAt
	}
	return 0
}

// A PingRequest specifies the string to echo in response.
// Fields are exported so that they will be serialized in the rpc call.
type PingRequest struct {
	// Echo this string with PingResponse.
	Ping string `protobuf:"bytes,1,opt,name=ping" json:"ping"`
	// The last offset the client measured with the server.
	Offset RemoteOffset `protobuf:"bytes,2,opt,name=offset" json:"offset"`
	// The address of the client.
	Addr                 string   `protobuf:"bytes,3,opt,name=addr" json:"addr"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{1}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

func (m *PingRequest) GetOffset() RemoteOffset {
	if m != nil {
		return m.Offset
	}
	return RemoteOffset{}
}

func (m *PingRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// A PingResponse contains the echoed ping request string.
type PingResponse struct {
	// An echo of value sent with PingRequest.
	Pong                 string   `protobuf:"bytes,1,opt,name=pong" json:"pong"`
	ServerTime           int64    `protobuf:"varint,2,opt,name=server_time,json=serverTime" json:"server_time"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{2}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func (m *PingResponse) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func init() {
	proto.RegisterType((*RemoteOffset)(nil), "proto.RemoteOffset")
	proto.RegisterType((*PingRequest)(nil), "proto.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "proto.PingResponse")
}

func init() { proto.RegisterFile("heartbeat.proto", fileDescriptor_3c667767fb9826a9) }

var fileDescriptor_3c667767fb9826a9 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x51, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x5d, 0xb7, 0x2b, 0x38, 0x5d, 0x10, 0xe2, 0x4b, 0x58, 0x04, 0xa5, 0x20, 0xf8, 0x62,
	0x17, 0xbd, 0x81, 0x5e, 0x60, 0xa5, 0xf8, 0xbe, 0xa4, 0x76, 0x9a, 0xcd, 0x43, 0x3a, 0x35, 0x99,
	0x7a, 0x46, 0x4f, 0xe1, 0x59, 0xa4, 0x93, 0xb5, 0x54, 0x7d, 0xca, 0xcc, 0xff, 0x4f, 0xe6, 0xfb,
	0x07, 0x2e, 0x0e, 0x68, 0x02, 0xd7, 0x68, 0xb8, 0xec, 0x03, 0x31, 0xa9, 0x95, 0x3c, 0x9b, 0x7b,
	0xeb, 0xf8, 0x30, 0xd4, 0xe5, 0x1b, 0xf9, 0xad, 0x25, 0x4b, 0x5b, 0x91, 0xeb, 0xa1, 0x95, 0x4e,
	0x1a, 0xa9, 0xd2, 0xaf, 0x82, 0x60, 0x5d, 0xa1, 0x27, 0xc6, 0x5d, 0xdb, 0x46, 0x64, 0x75, 0x05,
	0x67, 0x24, 0x95, 0x5e, 0xdc, 0x2c, 0xee, 0x96, 0xcf, 0xd9, 0xe7, 0xd7, 0xf5, 0x49, 0x75, 0xd4,
	0xd4, 0x06, 0x56, 0x18, 0x02, 0x05, 0x7d, 0x3a, 0x33, 0x93, 0xa4, 0x6e, 0x21, 0xf7, 0x68, 0xe2,
	0x10, 0xb0, 0xd9, 0x1b, 0xd6, 0xcb, 0xd9, 0x04, 0xfc, 0x18, 0x4f, 0x5c, 0x30, 0xe4, 0x2f, 0xae,
	0xb3, 0x15, 0xbe, 0x0f, 0x18, 0x59, 0x69, 0xc8, 0x7a, 0xd7, 0x59, 0xa1, 0x9d, 0x1f, 0xc7, 0x45,
	0x51, 0x0f, 0x53, 0x92, 0x11, 0x96, 0x3f, 0x5e, 0xa6, 0xc4, 0xe5, 0x3c, 0xee, 0x9f, 0x78, 0x1a,
	0x32, 0xd3, 0x34, 0x41, 0xd8, 0xd3, 0xb2, 0x51, 0x29, 0x76, 0xb0, 0x4e, 0xd4, 0xd8, 0x53, 0x17,
	0x51, 0xb0, 0xf4, 0x0f, 0x4b, 0x9d, 0x1d, 0xcf, 0x88, 0x18, 0x3e, 0x30, 0xec, 0xd9, 0x79, 0xfc,
	0x75, 0x28, 0x24, 0xe3, 0xd5, 0x79, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x87, 0x01, 0x76, 0x5b,
	0x7f, 0x01, 0x00, 0x00,
}
